/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianRoomsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/core/subgraph.ts
function computeSubgraph(linkGraph, startPath, depth) {
  const visited = /* @__PURE__ */ new Set();
  const notes = /* @__PURE__ */ new Set();
  const attachments = /* @__PURE__ */ new Set();
  const queue = [];
  queue.push({ path: startPath, currentDepth: 0 });
  while (queue.length > 0) {
    const { path, currentDepth } = queue.shift();
    if (visited.has(path)) continue;
    visited.add(path);
    const isAttachment = !path.endsWith(".md");
    if (isAttachment) {
      attachments.add(path);
    } else {
      notes.add(path);
    }
    if (currentDepth < depth || depth === 0) {
      if (!isAttachment) {
        const neighbors = linkGraph[path] || [];
        for (const neighbor of neighbors) {
          if (!visited.has(neighbor)) {
            queue.push({ path: neighbor, currentDepth: currentDepth + 1 });
          }
        }
      }
    }
  }
  return {
    notes: Array.from(notes),
    attachments: Array.from(attachments)
  };
}

// src/modals/SelectionModal.ts
var import_obsidian = require("obsidian");
var SelectionModal = class extends import_obsidian.Modal {
  // Store toggle components to update their UI
  constructor(app, notes, attachments, linkGraph, onConfirm) {
    super(app);
    this.attachmentToggles = {};
    this.notes = notes;
    this.attachments = attachments;
    this.linkGraph = linkGraph;
    this.onConfirm = onConfirm;
    this.selectedNotes = new Set(notes);
    this.selectedAttachments = new Set(attachments);
  }
  recalculateAttachments() {
    const neededAttachments = /* @__PURE__ */ new Set();
    for (const note of this.selectedNotes) {
      const links = this.linkGraph[note] || [];
      for (const link of links) {
        if (!link.endsWith(".md")) {
          neededAttachments.add(link);
        }
      }
    }
    for (const attachment of this.attachments) {
      if (!neededAttachments.has(attachment) && this.selectedAttachments.has(attachment)) {
        this.selectedAttachments.delete(attachment);
        if (this.attachmentToggles[attachment]) {
          this.attachmentToggles[attachment].setValue(false);
        }
      }
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Share to Obsidian Rooms" });
    contentEl.createEl("p", {
      text: `Review the ${this.notes.length} notes and ${this.attachments.length} attachments to sync.`
    });
    contentEl.createEl("h3", { text: "Notes" });
    const notesContainer = contentEl.createDiv({ cls: "obsidian-rooms-scroll-container" });
    notesContainer.style.maxHeight = "200px";
    notesContainer.style.overflowY = "auto";
    this.notes.forEach((note) => {
      new import_obsidian.Setting(notesContainer).setName(note).addToggle(
        (toggle) => toggle.setValue(this.selectedNotes.has(note)).onChange((value) => {
          if (value) this.selectedNotes.add(note);
          else this.selectedNotes.delete(note);
          this.recalculateAttachments();
        })
      );
    });
    contentEl.createEl("h3", { text: "Attachments" });
    const attachmentsContainer = contentEl.createDiv({ cls: "obsidian-rooms-scroll-container" });
    attachmentsContainer.style.maxHeight = "150px";
    attachmentsContainer.style.overflowY = "auto";
    this.attachments.forEach((attachment) => {
      new import_obsidian.Setting(attachmentsContainer).setName(attachment).addToggle((toggle) => {
        this.attachmentToggles[attachment] = toggle;
        toggle.setValue(this.selectedAttachments.has(attachment)).onChange((value) => {
          if (value) this.selectedAttachments.add(attachment);
          else this.selectedAttachments.delete(attachment);
        });
      });
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Sync to Web").setCta().onClick(() => {
      this.close();
      this.onConfirm(Array.from(this.selectedNotes), Array.from(this.selectedAttachments));
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  targetVaultName: ""
};
var ObsidianRoomsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Rooms Settings" });
    new import_obsidian2.Setting(containerEl).setName("API Key").setDesc("Your personal API key generated from the Obsidian Rooms dashboard.").addText((text) => {
      text.setPlaceholder("Enter your API key");
      text.inputEl.type = "password";
      text.setValue(this.plugin.settings.apiKey);
      text.onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Target Vault Name").setDesc('The name of the remote vault on Obsidian Rooms you want to sync notes to (e.g. "My Notes").').addText((text) => text.setPlaceholder("e.g. My Notes").setValue(this.plugin.settings.targetVaultName).onChange(async (value) => {
      this.plugin.settings.targetVaultName = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/modals/SyncProgressModal.ts
var import_obsidian3 = require("obsidian");
var SyncProgressModal = class extends import_obsidian3.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Syncing to Obsidian Rooms" });
    this.messageEl = contentEl.createEl("p", { text: "Initializing sync..." });
    this.progressBarEl = contentEl.createDiv({
      attr: {
        style: "width: 100%; height: 20px; background-color: var(--background-modifier-border); border-radius: 10px; overflow: hidden; margin-top: 10px;"
      }
    });
    this.progressFillEl = this.progressBarEl.createDiv({
      attr: {
        style: "width: 0%; height: 100%; background-color: var(--interactive-accent); transition: width 0.3s ease;"
      }
    });
  }
  onClose() {
    this.contentEl.empty();
  }
  updateProgress(message, percent) {
    if (this.messageEl) {
      this.messageEl.setText(message);
    }
    if (this.progressFillEl) {
      this.progressFillEl.style.width = `${Math.min(100, Math.max(0, percent))}%`;
    }
  }
  finish(success, message) {
    this.updateProgress(message, success ? 100 : 0);
    if (this.progressFillEl) {
      this.progressFillEl.style.backgroundColor = success ? "var(--text-success)" : "var(--text-error)";
    }
    const btn = this.contentEl.createEl("button", { text: "Close" });
    btn.style.marginTop = "20px";
    btn.onclick = () => this.close();
  }
};

// src/main.ts
var ObsidianRoomsPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    console.log("loading Obsidian Rooms plugin");
    await this.loadSettings();
    this.addSettingTab(new ObsidianRoomsSettingTab(this.app, this));
    this.addCommand({
      id: "add-to-shared-vault",
      name: "Add note to shared vault",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            this.openSelectionModal(activeFile);
          }
          return true;
        }
        return false;
      }
    });
  }
  openSelectionModal(file) {
    const depth = 0;
    const linkGraph = {};
    for (const [source, links] of Object.entries(this.app.metadataCache.resolvedLinks)) {
      linkGraph[source] = Object.keys(links);
    }
    const result = computeSubgraph(linkGraph, file.path, depth);
    new SelectionModal(this.app, result.notes, result.attachments, linkGraph, (notes, attachments) => {
      this.syncToWeb(notes, attachments);
    }).open();
  }
  async hashFile(file) {
    const buffer = await this.app.vault.readBinary(file);
    const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  async syncToWeb(notes, attachments) {
    var _a, _b;
    const apiKey = this.settings.apiKey;
    if (!apiKey) {
      new import_obsidian4.Notice("Please configure your API Key in settings.");
      return;
    }
    const vaultName = this.settings.targetVaultName;
    if (!vaultName) {
      new import_obsidian4.Notice("Please configure your Target Vault Name in settings.");
      return;
    }
    const progress = new SyncProgressModal(this.app);
    progress.open();
    try {
      progress.updateProgress("Computing hashes...", 10);
      const noteManifest = [];
      for (const path of notes) {
        const file = this.app.vault.getAbstractFileByPath(path);
        if (file instanceof import_obsidian4.TFile) {
          const hash = await this.hashFile(file);
          noteManifest.push({ path, hash });
        }
      }
      const attachmentManifest = [];
      for (const path of attachments) {
        const file = this.app.vault.getAbstractFileByPath(path);
        if (file instanceof import_obsidian4.TFile) {
          const hash = await this.hashFile(file);
          attachmentManifest.push({ path, hash });
        }
      }
      progress.updateProgress("Sending manifest to server...", 30);
      const manifestRes = await fetch(`https://obsidian-rooms.vercel.app/api/sync/manifest`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          apiKey,
          vaultName,
          notes: noteManifest,
          attachments: attachmentManifest
        })
      });
      if (!manifestRes.ok) {
        let errMsg = await manifestRes.text();
        try {
          const data = JSON.parse(errMsg);
          if (data.error) errMsg = data.error;
        } catch (e) {
        }
        progress.finish(false, `Manifest error: ${errMsg}`);
        return;
      }
      const manifestData = await manifestRes.json();
      const neededNotes = manifestData.neededNotes || [];
      const neededAttachments = manifestData.neededAttachments || [];
      if (neededNotes.length === 0 && neededAttachments.length === 0) {
        progress.finish(true, "Everything is already up to date!");
        return;
      }
      progress.updateProgress(`Preparing ${neededNotes.length} notes and ${neededAttachments.length} attachments...`, 50);
      const formData = new FormData();
      formData.append("apiKey", apiKey);
      formData.append("vaultName", vaultName);
      const noteAttachmentMap = {};
      const noteLinks = {};
      for (const path of notes) {
        const links = this.app.metadataCache.resolvedLinks[path] || {};
        const linkedAttachmentPaths = Object.keys(links).filter((p) => attachments.includes(p));
        const mapForNote = {};
        for (const p of linkedAttachmentPaths) {
          const hash = (_a = attachmentManifest.find((a) => a.path === p)) == null ? void 0 : _a.hash;
          if (hash) {
            const filename = p.split("/").pop() || p;
            mapForNote[filename] = hash;
          }
        }
        noteAttachmentMap[path] = mapForNote;
        const outgoingLinks = /* @__PURE__ */ new Set();
        for (const target of Object.keys(links)) {
          if (target.endsWith(".md")) {
            outgoingLinks.add(target);
          }
        }
        const unresolved = this.app.metadataCache.unresolvedLinks[path] || {};
        for (const target of Object.keys(unresolved)) {
          outgoingLinks.add(target);
        }
        noteLinks[path] = Array.from(outgoingLinks);
      }
      formData.append("noteAttachmentMap", JSON.stringify(noteAttachmentMap));
      formData.append("noteLinks", JSON.stringify(noteLinks));
      for (const path of neededNotes) {
        const file = this.app.vault.getAbstractFileByPath(path);
        if (file instanceof import_obsidian4.TFile) {
          const content = await this.app.vault.read(file);
          const hash = ((_b = noteManifest.find((n) => n.path === path)) == null ? void 0 : _b.hash) || "";
          formData.append("notePaths", path);
          formData.append("noteHashes", hash);
          formData.append("noteContents", content);
        }
      }
      for (const hash of neededAttachments) {
        const entry = attachmentManifest.find((a) => a.hash === hash);
        if (entry) {
          const file = this.app.vault.getAbstractFileByPath(entry.path);
          if (file instanceof import_obsidian4.TFile) {
            const buffer = await this.app.vault.readBinary(file);
            const blob = new Blob([buffer]);
            formData.append("attachmentPaths", entry.path);
            formData.append("attachmentHashes", hash);
            formData.append("attachmentBlobs", blob, entry.path);
          }
        }
      }
      progress.updateProgress("Uploading data to Obsidian Rooms...", 80);
      const uploadRes = await fetch(`https://obsidian-rooms.vercel.app/api/sync/upload`, {
        method: "POST",
        body: formData
      });
      if (!uploadRes.ok) {
        let errMsg = await uploadRes.text();
        try {
          const data = JSON.parse(errMsg);
          if (data.error) errMsg = data.error;
        } catch (e) {
        }
        progress.finish(false, `Upload error: ${errMsg}`);
        return;
      }
      progress.finish(true, "Sync complete!");
    } catch (err) {
      console.error(err);
      progress.finish(false, "Failed to sync. Check console.");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    console.log("unloading Obsidian Rooms plugin");
  }
};
